### PR TITLE
Update to new syntax, rework buildscript a little bit, add BLAS

### PR DESCRIPTION
**Pull request by staticfloat**
List of changes:

* First and foremost, uses new `build_tarballs()` function instead of `autobuild()`, which is the [fundamental API point](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/8cd7675e86ab59300616e446abf68095e9575e49/src/AutoBuild.jl#L5-L16) for generating tarballs nowadays.

* Moves patches out into separate `patches` directory, which gets bundled up and brought into `$WORKSPACE/srcdir` by listing it as one of the "sources".

* Adds `OpenBLASBuilder` as a `dependency`, which causes `libopenblas.so` to be installed into `$prefix/lib`.  Tells the build system about it, and patches the CMake files to know about our ILP64 renaming (e.g. `dcopy` is actually called `dcopy_64` on 64-bit platforms)

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Wow, looks great!

**Comment by ChrisRackauckas** [comment]
libsundials_sunlinsolklu is missing after this PR and I can't find out how to get it back. For some reason it wasn't in the previous build_tarballs but it was in the build.jl

https://github.com/JuliaDiffEq/Sundials.jl/blob/master/deps/build.jl#L21

**Comment by staticfloat** [comment]
Isn't it right here? https://github.com/JuliaDiffEq/SundialsBuilder/blob/b94699dd806f8f3d59a5006e2613eb294efc1438/build_tarballs.jl#L95

**Comment by ChrisRackauckas** [comment]
But then I get

```julia
julia> Pkg.build("Sundials")
INFO: Building SpecialFunctions
INFO: Building DiffEqBase
INFO: ~~~ DifferentialEquations.jl *BREAKING* changes  ~~~

We have changed the front-end API on how
users may define equations of motion and
problems, for all problem types that can
be used in the DifferentialEquations.jl.
These are *BREAKING* changes, and they
also have *NO WARNINGS*!

Please see our latest documentation here:
http://docs.juliadiffeq.org/latest/

or the blogpost that describes the changes:
http://juliadiffeq.org/2018/01/24/Parameters.html

In short, the mutated argument is the first argument,
and parameters are now directly passed
into the equations of motion function. For all
types now mutation goes first, then dependent variables,
then parameters, then independent variables.

`f(mutated, dependent variables, p/integrator, independent variables)`

For example, this means that the ODE syntax will be `f(u,p,t)` (for the
out-of-place) and `f(du,u,p,t)` (for the in-place). Notice
that this change also removes the need for ParameterizedFunctions
as now parameters are part of the equations of motion.

For more details please visit the above links!
INFO: Building Sundials
Info: Downloading https://github.com/JuliaDiffEq/SundialsBuilder/releases/download/sundials-3.1.1.2/
Sundials.x86_64-w64-mingw32.tar.gz to C:\Users\Chris\.julia\v0.6\Sundials\deps\usr\downloads\Sundial
s.x86_64-w64-mingw32.tar.gz...
========================================[ ERROR: Sundials ]=========================================

LoadError: BinaryProvider.LibraryProduct("C:\\Users\\Chris\\.julia\\v0.6\\Sundials\\deps\\usr\\bin",
 String["libsundials_sunlinsolklu"], :libsundials_sunlinsolklu, "Prefix(C:\\Users\\Chris\\.julia\\v0
.6\\Sundials\\deps\\usr)") is not satisfied, cannot generate deps.jl!
while loading C:\Users\Chris\.julia\v0.6\Sundials\deps\build.jl, in expression starting on line 63

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("Sundials")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================
```

**Comment by tshort** [comment]
Travis isn't showing the output of the Sundials compilation. Could you try to build it locally to see if KLU is getting built?

**Comment by tshort** [comment]
The only difference I see in the CMake portion of the build script is that the old version had a `-DCMAKE_FIND_ROOT_PATH="$WORKSPACE/destdir"`. I can't remember the details, but I do remember it was tricky to get Sundials to recognize KLU across platforms.

**Comment by staticfloat** [comment]
On Linux, I can verify that KLU is getting built, and I can `dlopen()` the built `libsundials_sunlinsolklu.so`.

Perhaps this is a problem with the Windows build.  I can verify that KLU is getting built on the windows machine..... I wonder if there's some dependent library that it's not finding.  What happens if you try to directly `dlopen()` the `libsundials_sunlinsolklu.dll`?

**Comment by tshort** [comment]
In the windows tarball, that dll is missing.

**Comment by ChrisRackauckas** [comment]
@tshort all of the ones with KLU you built outside of BinaryBuilder I think?

**Comment by staticfloat** [comment]
Aha, looks like the update to 3.1.1 broke one of the patches.  I'll submit a PR to fix that.  Also, now that `build_tarballs.jl --debug` is a thing, I'm pretty sure a future version of `BinaryBuilder` is going to add `set -e` to the beginning of your script, which will cause it to error out if any command doesn't complete successfully.  This will catch problems like this more reliably.

**Comment by ChrisRackauckas** [comment]
>I'm pretty sure a future version of BinaryBuilder is going to add set -e to the beginning of your script, which will cause it to error out if any command doesn't complete successfully. This will catch problems like this more reliably.

Oh! I thought Travis would error if a command didn't complete successfully. Yes, it would be a good thing to make it the default.

**Comment by tshort** [comment]
I was using BinaryBuilder, but I built everything locally (no Travis). The KLU part is tricky because the build doesn't error out if it can't find KLU. It just builds it without KLU.

**Comment by staticfloat** [comment]
In this case, you can build with `--verbose` and see what the CMake configuration says about finding KLU, which is helpful.

**Pull request merged**
